name: Security Scan

# When to run the scan
on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write
  checks: write
  id-token: write

jobs:
  secret-scan:
    uses: richlamdev/richlamdev-actions/.github/workflows/gitleaks-scan-reusable.yml@main
    with:
      scan-mode: full
      config-path: .gitleaks.toml
      gitleaks-flags: ''
    secrets: inherit
