name: Security Scan

# When to run the scan
on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  secret-scan:
    uses: richlamdev/richlamdev-actions/.github/workflows/gitleaks-scan-reusable.yml@main
    with:
      scan-mode: latest-commit
      config-path: .gitleaks.toml
      gitleaks-flags: ''
    # secrets:
    #   GITLEAKS_LICENSE_KEY: ${{ secrets.GITLEAKS_LICENSE }}
